version: '3.7'

services: 
  latex:
    build: ./latex
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./latex/workspace:/root/
      - /root/.ssh:/root/.ssh/
    ports:
      - '0.0.0.0:2222:22'
